"""
FOFOCA — Dog Monitoring Module

Tracks pet dogs inside the home using vision (YOLOv8) and audio (YAMNet)
pipelines. Monitors activity, barking patterns, feeding times, and
overall wellbeing.

All monitoring data is governed by ThinkNEO and stored in ChromaDB
for long-term behavioral analysis.
"""

import json
import logging
import time
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

logger = logging.getLogger("fofoca.dog_monitor")


# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------


class DogActivity(Enum):
    SLEEPING = "sleeping"
    RESTING = "resting"
    WALKING = "walking"
    RUNNING = "running"
    EATING = "eating"
    DRINKING = "drinking"
    PLAYING = "playing"
    BARKING = "barking"
    WHINING = "whining"
    UNKNOWN = "unknown"


class AlertLevel(Enum):
    INFO = "info"
    WARNING = "warning"
    ALERT = "alert"
    URGENT = "urgent"


@dataclass
class DogState:
    """Current state of a monitored dog."""
    name: str
    last_seen: str = ""
    last_seen_room: str = ""
    current_activity: DogActivity = DogActivity.UNKNOWN
    confidence: float = 0.0
    bark_count_last_hour: int = 0
    last_fed: Optional[str] = None
    last_walk: Optional[str] = None
    activity_log: list = field(default_factory=list)


@dataclass
class DogAlert:
    """Alert generated by the dog monitoring system."""
    alert_level: AlertLevel
    dog_name: str
    message: str
    recommended_action: str
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    data: Optional[dict] = None


# ---------------------------------------------------------------------------
# Dog Monitor
# ---------------------------------------------------------------------------


class DogMonitor:
    """
    Monitors household dogs using vision and audio sensors.

    This is a skeleton implementation. In production, it subscribes to
    MQTT topics for real-time vision detections and audio events.
    """

    def __init__(
        self,
        thinkneo_brain=None,
        mqtt_client=None,
        chroma_client=None,
        known_dogs: Optional[list[str]] = None,
    ):
        """
        Args:
            thinkneo_brain: FofocaBrain instance for reasoning about dog behavior.
            mqtt_client: Paho MQTT client for sensor data.
            chroma_client: ChromaDB client for behavioral history.
            known_dogs: List of known dog names.
        """
        self.brain = thinkneo_brain
        self.mqtt = mqtt_client
        self.chroma = chroma_client
        self.dogs: dict[str, DogState] = {}

        for name in (known_dogs or []):
            self.dogs[name] = DogState(name=name)

        logger.info(
            "DogMonitor initialized — tracking %d dogs: %s",
            len(self.dogs),
            ", ".join(self.dogs.keys()),
        )

    # ------------------------------------------------------------------
    # Vision processing
    # ------------------------------------------------------------------

    def process_vision_frame(self, detections: list[dict], room: str) -> list[DogAlert]:
        """
        Process a frame of YOLOv8 detections for dog-related events.

        Args:
            detections: List of detection dicts with class, confidence, bbox.
            room: Room where the detection occurred.

        Returns:
            List of DogAlert objects for any notable events.
        """
        alerts = []
        now = datetime.now(timezone.utc).isoformat()

        dog_detections = [
            d for d in detections
            if d.get("class") == "dog" and d.get("confidence", 0) > 0.5
        ]

        for detection in dog_detections:
            # Assign to nearest known dog (simplified — in production use
            # re-identification or tracking)
            dog_name = self._identify_dog(detection)
            if dog_name not in self.dogs:
                self.dogs[dog_name] = DogState(name=dog_name)

            dog = self.dogs[dog_name]
            dog.last_seen = now
            dog.last_seen_room = room
            dog.confidence = detection.get("confidence", 0)

            # Estimate activity from detection context
            activity = self._estimate_activity(detection)
            if activity != dog.current_activity:
                old_activity = dog.current_activity
                dog.current_activity = activity
                dog.activity_log.append({
                    "from": old_activity.value,
                    "to": activity.value,
                    "time": now,
                    "room": room,
                })
                logger.info(
                    "Dog '%s' activity: %s -> %s (room: %s)",
                    dog_name, old_activity.value, activity.value, room,
                )

        # Check for missing dogs (not seen in a while)
        for name, dog in self.dogs.items():
            if dog.last_seen and self._minutes_since(dog.last_seen) > 30:
                alerts.append(DogAlert(
                    alert_level=AlertLevel.WARNING,
                    dog_name=name,
                    message=f"Dog '{name}' not seen for 30+ minutes",
                    recommended_action=f"Navigate to last known location: {dog.last_seen_room}",
                ))

        return alerts

    # ------------------------------------------------------------------
    # Audio processing
    # ------------------------------------------------------------------

    def process_audio_event(self, event: dict) -> Optional[DogAlert]:
        """
        Process an audio event from YAMNet classification.

        Args:
            event: Dict with type (bark, whine, etc.), confidence, duration_ms.

        Returns:
            DogAlert if the event warrants attention, None otherwise.
        """
        event_type = event.get("type", "")
        confidence = event.get("confidence", 0)
        duration_ms = event.get("duration_ms", 0)

        if event_type == "bark" and confidence > 0.7:
            # Increment bark counter for all known dogs
            # (in production, use audio localization to attribute)
            for dog in self.dogs.values():
                dog.bark_count_last_hour += 1
                dog.current_activity = DogActivity.BARKING

                if dog.bark_count_last_hour > 20:
                    return DogAlert(
                        alert_level=AlertLevel.ALERT,
                        dog_name=dog.name,
                        message=(
                            f"Excessive barking: {dog.bark_count_last_hour} barks "
                            f"in the last hour"
                        ),
                        recommended_action=(
                            "Navigate to dog's location, assess situation, "
                            "consider calming interaction or owner notification"
                        ),
                        data={
                            "bark_count": dog.bark_count_last_hour,
                            "last_bark_confidence": confidence,
                            "last_bark_duration_ms": duration_ms,
                        },
                    )

        elif event_type == "whine" and confidence > 0.7:
            for dog in self.dogs.values():
                dog.current_activity = DogActivity.WHINING
                return DogAlert(
                    alert_level=AlertLevel.WARNING,
                    dog_name=dog.name,
                    message=f"Dog whining detected (confidence: {confidence:.2f})",
                    recommended_action=(
                        "Check on dog — whining may indicate distress, "
                        "pain, or need for attention"
                    ),
                    data=event,
                )

        return None

    # ------------------------------------------------------------------
    # Feeding tracking
    # ------------------------------------------------------------------

    def record_feeding(self, dog_name: str, food_type: str = "regular"):
        """Record a feeding event for a dog."""
        now = datetime.now(timezone.utc).isoformat()
        if dog_name in self.dogs:
            self.dogs[dog_name].last_fed = now
            logger.info("Feeding recorded for '%s' at %s — %s", dog_name, now, food_type)
        else:
            logger.warning("Unknown dog: %s", dog_name)

    def check_feeding_schedule(self) -> list[DogAlert]:
        """Check if any dogs are overdue for feeding."""
        alerts = []
        for name, dog in self.dogs.items():
            if dog.last_fed and self._hours_since(dog.last_fed) > 8:
                alerts.append(DogAlert(
                    alert_level=AlertLevel.ALERT,
                    dog_name=name,
                    message=f"Dog '{name}' has not been fed for 8+ hours",
                    recommended_action="Notify owner about missed feeding",
                ))
        return alerts

    # ------------------------------------------------------------------
    # Status reporting
    # ------------------------------------------------------------------

    def get_status(self) -> dict:
        """Get current status of all monitored dogs."""
        return {
            name: {
                "activity": dog.current_activity.value,
                "last_seen": dog.last_seen,
                "last_seen_room": dog.last_seen_room,
                "bark_count_last_hour": dog.bark_count_last_hour,
                "last_fed": dog.last_fed,
                "confidence": dog.confidence,
            }
            for name, dog in self.dogs.items()
        }

    def get_daily_report(self) -> str:
        """Generate a daily activity report for all dogs."""
        report_lines = ["FOFOCA Dog Monitor — Daily Report", "=" * 40]
        for name, dog in self.dogs.items():
            report_lines.extend([
                f"\nDog: {name}",
                f"  Current activity: {dog.current_activity.value}",
                f"  Last seen: {dog.last_seen_room} at {dog.last_seen}",
                f"  Barks (last hour): {dog.bark_count_last_hour}",
                f"  Last fed: {dog.last_fed or 'unknown'}",
                f"  Activity changes today: {len(dog.activity_log)}",
            ])
        return "\n".join(report_lines)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _identify_dog(self, detection: dict) -> str:
        """
        Identify which known dog a detection belongs to.
        Skeleton: returns first known dog or 'unknown_dog'.
        In production: use re-identification embeddings.
        """
        if self.dogs:
            return list(self.dogs.keys())[0]
        return "unknown_dog"

    def _estimate_activity(self, detection: dict) -> DogActivity:
        """
        Estimate dog activity from detection context.
        Skeleton: returns RESTING by default.
        In production: analyze bbox movement, pose estimation.
        """
        return DogActivity.RESTING

    def _minutes_since(self, iso_timestamp: str) -> float:
        """Calculate minutes elapsed since an ISO timestamp."""
        try:
            then = datetime.fromisoformat(iso_timestamp)
            now = datetime.now(timezone.utc)
            return (now - then).total_seconds() / 60
        except (ValueError, TypeError):
            return 0

    def _hours_since(self, iso_timestamp: str) -> float:
        """Calculate hours elapsed since an ISO timestamp."""
        return self._minutes_since(iso_timestamp) / 60


# ---------------------------------------------------------------------------
# Standalone test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    monitor = DogMonitor(known_dogs=["Rex", "Luna"])

    # Simulate vision frame
    test_detections = [
        {"class": "dog", "confidence": 0.93, "bbox": [50, 100, 200, 300]},
        {"class": "person", "confidence": 0.88, "bbox": [400, 100, 600, 500]},
    ]
    alerts = monitor.process_vision_frame(test_detections, room="living_room")
    for alert in alerts:
        print(f"ALERT: {alert.message}")

    # Simulate barking
    for i in range(25):
        alert = monitor.process_audio_event({
            "type": "bark",
            "confidence": 0.85,
            "duration_ms": 800,
        })
        if alert:
            print(f"ALERT: {alert.message}")

    # Print status
    print(f"\nStatus: {json.dumps(monitor.get_status(), indent=2)}")
    print(f"\n{monitor.get_daily_report()}")
